apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: pt232/catalog-service
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
          env:
            - name: LOGGER_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: gca-config
                  key: logger-level
            - name: CATALOG_USER
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: catalog-user
            - name: CATALOG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: catalog-password
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
