apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
        tier: application
    spec:
      containers:
        - name: checkout
          image: pt232/checkout-service
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
          env:
            - name: LOGGER_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: gca-config
                  key: logger-level
            - name: HOST_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: gca-config
                  key: host-address
            - name: CHECKOUT_USER
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: checkout-user
            - name: CHECKOUT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: checkout-password
            - name: CART_USER
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: cart-user
            - name: CART_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: cart-password
            - name: SHIPPING_USER
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: shipping-user
            - name: SHIPPING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: shipping-password
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: checkout-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkout-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
