apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: pt232/checkout-service
          ports:
            - containerPort: 8083
          env:
            - name: LOGGER_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: gca-config
                  key: logger-level
            - name: HOST_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: gca-config
                  key: host-address
