apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: pt232/shipping-service
          ports:
            - containerPort: 8082
          env:
            - name: LOGGER_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: gca-config
                  key: logger-level
            - name: HOST_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: gca-config
                  key: host-address
            - name: SHIPPING_USER
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: shipping-user
            - name: SHIPPING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gca-secret
                  key: shipping-password
