server:
  port: 8081

logging.level.com.whsgcashop.cart: ${LOGGER_LEVEL:INFO}

gca.host.property.value: ${HOST_ADDRESS:http://gca-shop.local/}

resilience4j.timelimiter:
  instances:
    cartService:
      timeoutDuration: 2s
      cancelRunningFuture: true
resilience4j.retry:
  instances:
    cartService:
      maxRetryAttempts: 3
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10
      failureRateThreshold: 60
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
  instances:
    cartService:
      baseConfig: default
resilience4j.bulkhead:
  instances:
    cartService:
      maxConcurrentCalls: 10
      maxWaitDuration: 10ms
resilience4j.ratelimiter:
  instances:
    cartService:
      limitForPeriod: 5
      limitRefreshPeriod: 60s
      timeoutDuration: 0