export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const GET_CART_ENTRIES = "GET_CART_ENTRIES";
export const GET_CART_ENTRIES_AMOUNT = "GET_CART_ENTRIES_AMOUNT";
export const GET_TOTAL_COST = "GET_TOTAL_COST";
export const ADD_CART_ENTRY = "ADD_CART_ENTRY";
export const DELETE_CART_ENTRIES = "DELETE_CART_ENTRIES";
export const CART_ERROR = "CART_ERROR";

export const GET_SHIPPING_COST = "GET_SHIPPING_COST";
export const SHIPPING_ERROR = "SHIPPING_ERROR";

export const GET_CHECKOUT_ORDER = "GET_CHECKOUT_ORDER";
export const CHECKOUT_ERROR = "CHECKOUT_ERROR";
