server:
  port: 8080

logging.level.com.whsgcashop.catalog: ${LOGGER_LEVEL:INFO}

gca.user.property.value: ${CATALOG_USER:catalogUser}
gca.password.property.value: ${CATALOG_PASSWORD:catalogPass}

resilience4j.timelimiter:
  instances:
    catalogService:
      timeoutDuration: 2s
      cancelRunningFuture: true
resilience4j.retry:
  instances:
    catalogService:
      maxRetryAttempts: 3
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10
      failureRateThreshold: 60
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
  instances:
    catalogService:
      baseConfig: default
resilience4j.bulkhead:
  instances:
    catalogService:
      maxConcurrentCalls: 10
      maxWaitDuration: 10ms
resilience4j.ratelimiter:
  instances:
    catalogService:
      limitForPeriod: 5
      limitRefreshPeriod: 60s
      timeoutDuration: 0